name: Publish Python 🐍 distributions 📦 to TestPyPI

on:
  push:
    branches:
      - master
      - support/3.x

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://test.pypi.org/p/django-sql-explorer
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Install npm dependencies
      run: npm install
    - name: Build client
      run: npm run build

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip_existing: true
